import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { IJWTPayload } from "@/types/jwt-payload";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body>
          <Header />
          <main className="flex-grow min-h-150 mt-10 mb-10">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </>
  );
}
